name: Trigger Airflow

on:
  push:
    branches:
      - main
    paths:
      - '**.reqif'
  pull_request:
    branches:
      - main
    paths:
      - '**.reqif'
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Get changed files
      id: get_changed_files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
        fi

    - name: Trigger Airflow
      env:
        ENDPOINT: https://ccd0-113-161-83-56.ngrok-free.app
        PATH: /api/v1/dags/thethree_reqif_to_rst/dagRuns
        USERNAME: airflow
        PASSWORD: airflow
      run: |
        changed_files="["
        
        for file in ${{ steps.get_changed_files.outputs.changed_files }}; do
          content=$(cat "$file" | gzip | base64 -w0)
          changed_files+="{'name': '$file', 'content': '$content'},"
        done
        
        changed_files="${changed_files%?}" # Remove the trailing comma
        changed_files+="]"
        
        payload="
        {
          'conf': {
            'reqif_files': $changed_files
          },
          'note': 'Trigger from Github Action'
        }
        "
        payload="${payload//\'/\"}"
        
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: True" \
          --user "$USERNAME:$PASSWORD" \
          -d "$payload" \
          "$ENDPOINT""$PATH"
