name: Trigger Airflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: file_changes
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD^...HEAD)"

    - name: Retrieve file content
      id: file_content
      run: |
        changed_files="${{ steps.file_changes.outputs.files }}"
        file_content="["
        IFS=$'\n'   # Set the input field separator to newline
        for file in $changed_files; do
          content=$(cat "$file")
          escaped_content=$(echo "$content" | jq -Rs '@uri')
          file_content+="{\"name\": \"$file\", \"content\": \"$escaped_content\"},"
        done
        file_content="${file_content%?}" # Remove the trailing comma
        file_content+="]"
        echo "::set-output name=contents::$file_content"

    - name: Trigger Airflow
      env:
        API_ENDPOINT: https://879d-42-115-94-181.ngrok-free.app
      run: |
        changed_files="${{ steps.file_changes.outputs.files }}"
        content="${{ steps.file_content.outputs.content }}"
        payload='{"branch": "main", "message": "Files have been changed.", "files": "'"$changed_files"'", "contents": "'"$contents"'"}'
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: True" \
          -d "$payload" \
          $API_ENDPOINT
