name: Trigger Airflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Get changed files
      id: changed_files
      run: |
        if ${{ github.event_name == 'pull_request' }}; then
          echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
        else
            echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
        fi

    - name: Retrieve file content
      id: changed_files_content
      run: |
        payload="["
        IFS=$'\n'   # Set the input field separator to newline
        for file in ${{ steps.changed_files.outputs.changed_files }}; do
          content=$(cat "$file")
          escaped_content=$(echo "$content" | jq -Rs '@uri')
          payload+="{\"name\": \"$file\", \"content\": \"$escaped_content\"},"
        done
        payload="${payload%?}" # Remove the trailing comma
        payload+="]"
        echo "changed_files_payload=$payload" >> $GITHUB_OUTPUT

    - name: Trigger Airflow
      env:
        API_URL: https://a275-42-115-94-181.ngrok-free.app/api/v1/dags/thethree_reqif_to_rst/dagRuns 
        USERNAME: airflow
        PASSWORD: airflow
      run: |
        changed_files="${{ steps.changed_files_content.outputs.changed_files_payload }}"
        payload='
        {
          "dag_run_id": "thethree_reqif_to_rst",
          "conf": {
            "branch": "main", 
            "message": "Files have been changed.", 
            "reqif_files": "'"$changed_files"'"
          },
          "note": "Trigger from Github Action"
        }
        '
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: True" \
          --user "$USERNAME:$PASSWORD"
          -d "$payload" \
          $API_URL
