name: Trigger Airflow

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Airflow
      env:
        API_ENDPOINT: https://879d-42-115-94-181.ngrok-free.app
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: True" \
          -d '{"branch": "main", "message": "Files have been changed."}' \
          $API_ENDPOINT
