name: Trigger Airflow

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: file_changes
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD^..HEAD)"

    - name: Trigger Airflow
      env:
        API_ENDPOINT: https://879d-42-115-94-181.ngrok-free.app
      run: |
        changed_files=$(echo "${{ steps.file_changes.outputs.files }}" | tr '\n' ',')
        payload='{"branch": "main", "message": "Files have been changed.", "changed_files": "'"$changed_files"'"}'
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "ngrok-skip-browser-warning: True" \
          -d "$payload" \
          $API_ENDPOINT
